SAGEMAKER_CHECKPOINT_DIR = '/opt/ml/checkpoints'
SAGEMAKER_SAMPLE_DIR = '/opt/ml/model/samples'
SAGEMAKER_HYPERPARAMETERS_PATH = '/opt/ml/input/config/hyperparameters.json'
SAGEMAKER_MODEL_PATH = '/opt/ml/input/data/gpt-2/'
SAGEMAKER_INPUT_PATH = '/opt/ml/input/data/text/input.txt'
